# Generated by Django 4.2 on 2024-10-23 19:33

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=150)),
                ('brand_nationality', django_countries.fields.CountryField(max_length=2)),
                ('model', models.CharField(max_length=150, unique=True)),
                ('price', models.PositiveBigIntegerField()),
                ('color', models.CharField(max_length=150)),
                ('screen_size', models.FloatField()),
                ('is_availble', models.BooleanField()),
                ('made_in', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
