# Generated by Django 4.2 on 2024-10-24 14:58

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='brand_name',
            field=models.CharField(max_length=150, verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='brand_nationality',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='ملیت برند'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='color',
            field=models.CharField(max_length=150, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='is_availble',
            field=models.BooleanField(verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='made_in',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='کشور سازنده'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='model',
            field=models.CharField(max_length=150, unique=True, verbose_name='مدل'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='screen_size',
            field=models.FloatField(verbose_name='سایز صفحه نمایش'),
        ),
    ]
